### ISSUE TITLE
Opt-out is broken

### ISSUE THREAD

**Issue by brortao** [distsn/vinayaka#171]
I can find several accounts that have #nobot in their profile, but a) they still show up in search and b) you can still find users related to them.

This seems like a major concern, and is potentially a breach of GDPR -- the ability to restrict processing/to opt out is a major part of that law.

**Comment by hakaba-hitoyo** [comment]
WTF Mastodon sends awful code such as `#\u003cspan\u003enobot\u003c/span\u003e` as their bio.

**Comment by brortao** [comment]
yeah, the best way to check for nobot is just to check for that string without the hashtag.

there’s only one word in the english dictionary that contains that substring — ethnobotany — and it’s not used very often so there won’t be (m)any false positives!

**Comment by hakaba-hitoyo** [comment]
https://github.com/distsn/vinayaka/commit/3d67113302eced3e1b0906be607cdbd8e8e8ee5e seems to work well.
