### ISSUE TITLE
"Access-Control-Allow-Origin" was not specified

### ISSUE THREAD

**Issue by neetshin** [distsn/vinayaka#46]
開発お疲れ様です．

#### やりたいこと
- 自分が保有するドメイン上にあるWebアプリケーションのフロントエンドからマッチングAPIを利用したい．

#### 問題
- APIのレスポンスヘッダに `Access-Control-Allow-Origin` が不足しているので，ブラウザはこれをセキュリティ上の問題で解決できない．

画像：
![2018-01-04 13 34 04](https://user-images.githubusercontent.com/19276905/34554663-00c22ee4-f154-11e7-8b81-b00aa4b4d5a6.png)

#### 解決策
- レスポンスヘッダに`Access-Control-Allow-Origin: *`を追加してください．(必要であれば `Access-Control-Allow-Methods` なども)

#### 参考
* https://developer.mozilla.org/ja/docs/Web/HTTP/HTTP_access_control

**Comment by hakaba-hitoyo** [comment]
Access-Control-Allow-Origin: * を付けました。これで XHR できるようになったかは動作確認をしていないので不明です。

**Comment by neetshin** [comment]
無事動きました．ご対応ありがとうございます．
