### ISSUE TITLE
"bio" returns unexpected empty string

### ISSUE THREAD

**Issue by neetshin** [distsn/vinayaka#48]
マッチングAPIで返されるオブジェクトにある `bio` ってアカウントのプロフィールのことだと思うのですが，これが毎回空の文字列を返しています．

パースしたペイロード：
![2018-01-05 12 55 04](https://user-images.githubusercontent.com/19276905/34599332-b0eaf3d2-f217-11e7-8bb0-8bfaa12421b1.png)

**Comment by hakaba-hitoyo** [comment]
bio が空文字列なのは、ネットワーク負荷を軽減するために意図的にそうしていたのですが、ないと不便な気もするし、いまの環境ではネットワーク負荷の軽減がそれほど重要でないので、復活させるかもしれません。

**Comment by hakaba-hitoyo** [comment]
bio が空文字列になった様子です。
https://github.com/distsn/vinayaka/issues/45
https://github.com/distsn/vinayaka/commit/ce58deeb7bd61cd4a3a05e8ecd4b36e93e366aa8

**Comment by hakaba-hitoyo** [comment]
bio に bio が入るようになったと思います。

**Comment by neetshin** [comment]
仕様でしたか...失礼しました 🙏 ご対応ありがとうございます
