### ISSUE TITLE
White-space returns as an unescaped character (?)

### ISSUE THREAD

**Issue by neetshin** [distsn/vinayaka#49]
マッチングAPIの`bio`と`screen_name`に半角スペースが含まれている場合，その半角スペースが「�」(`U+FFFD`)として返されています．

![2018-01-07 21 29 53](https://user-images.githubusercontent.com/19276905/34651125-ee672fba-f3f1-11e7-8b3c-9911b4a06efd.png)

知識不足でソースコードレベルでの指摘ができず申し訳ないです 🙏

**Comment by hakaba-hitoyo** [comment]
プログラムを修正しましたが、データが更新されるまで12時間くらいかかります...

**Comment by hakaba-hitoyo** [comment]
これは自分用のメモなのですが、言語モデルのスペースを�に置換しなくなったので、英語圏のユーザーの検索結果が (長期的には) 改善されるかもしれない。
https://github.com/distsn/vinayaka/commit/648ddaa4ea0b12a63d9ac06175924dea0d4825a9#diff-e929c6b17663e29826a593fcca45e48f
