### ISSUE TITLE
Why is everything assortedflotsam.com blacklisted?

### ISSUE THREAD

**Issue by smeggysmeg** [distsn/vinayaka#73]
Hi there,

I'm the instance admin at assortedflotsam.com and I'm just curious why the entire instance is included in the blacklist. Was there a specific harassment incident?

Thanks for any info.

**Comment by hakaba-hitoyo** [comment]
assortedflotsam.com has too meny bots. (`@politicsbot`, `@NewsBot`, `@technewsbot`, ...)

Too few organic post.

**Comment by hakaba-hitoyo** [comment]
assortedflotsam.com's local timeline:

http://distsn.org/instance-preview.html?assortedflotsam.com

**Comment by smeggysmeg** [comment]
I understand. They are news feeds, not advertising or spam, but I understand not wanting bots.

I just wanted to make sure it wasn't harassment or abuse.

Thanks!
